name: Build & Publish with Compose

on:
  push:
    branches: [ master ]

  schedule:
    # every day at 19:30 UTC
    - cron: '00 12 * * *'

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU (multi-arch, optional)
        uses: docker/setup-qemu-action@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push with Compose
        uses: docker/compose-action@v3.2.0
        with:
          files: docker-compose.yml
          push: true
          services: |
            trainer
            predictor
